config/routes.rb
Rails.application.routes.draw do

  root to:  'homes#top'
  get '/about' => 'homes#about'

  devise_for :admins, controllers: {
  sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
  sessions: 'public/users/sessions',
  registrations: 'public/users/registrations',
  passwords: 'public/users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/users/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :articles do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update]
    resources :quizzes, only: [:new, :create, :show]
    resources :contacts, only: [:new, :create, :show]
    resources :searches, only: [:index]
    resources :items, only: [:index]
    resources :favorites, only: [:create, :destroy]
  end

  namespace :admins do
    resources :articles
    resources :quizzes, only: [:index, :create, :edit, :update, :destroy]
    resources :contacts, only: [:index, :show]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :rememberable,
         :validatable#, :recoverable#, :registerable

  has_many :articles, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user, optional: true
  belongs_to :admin, optional: true
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :article_tag_relations, dependent: :destroy
  has_many :tags, through: :article_tag_relations, dependent: :destroy

  attachment :image

  enum level: { 初級: 0, 中級: 1, 上級: 2 }

  validates :title, presence: true, length: {maximum: 50}
  validates :body, presence: true
  validates :level, presence: true

  def reading_time
    reading_time = body.length / 300
    if reading_time < 1
      p "読了目安時間 1分以内"
    else
      p ("読了目安時間 #{reading_time}分")
    end
  end


  def self.search(search)
    Article.where(['title LIKE ?', "%#{search}%"])
  end

end

app/models/article_tag_relation.rb
class ArticleTagRelation < ApplicationRecord

  belongs_to :article
  belongs_to :tag

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :article

  validates :comment, presence: true
  
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :title, presence: true, length: {maximum: 50}
  validates :message, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :article
  
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user

end

app/models/itemimage_tag.rb
class ItemimageTag < ApplicationRecord
  
  belongs_to :user
  
end

app/models/quiz.rb
class Quiz < ApplicationRecord

  has_many :results, dependent: :destroy

  validates :question, presence: true
  validates :choice1, presence: true
  validates :choice2, presence: true
  validates :answer, presence: true
  validates :level, presence: true

  enum level: { 初級: 0, 中級: 1, 上級: 2 }

  def get_answer
    eval("choice#{answer}")
  end

  class << self

    def quiz_set
      low = Quiz.where(level: '初級').sample(10)
      middle = Quiz.where(level: '中級').sample(10)
      high = Quiz.where(level: '上級').sample(10)
      set = low + middle + high
      set.sort
    end

  end

end

app/models/result.rb
class Result < ApplicationRecord
  before_create :judge_answer

  belongs_to :score
  belongs_to :quiz

  validates :selection_result, presence: true

  def judge_answer
    quiz = Quiz.find(self.quiz_id)
    if selection_result == quiz.answer
      self.judgement = 'true'
    else
      self.judgement = 'false'
    end
  end

end

app/models/score.rb
class Score < ApplicationRecord

  belongs_to :user
  has_many :results, dependent: :destroy
  accepts_nested_attributes_for :results

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :article_tag_relations, dependent: :destroy
  has_many :articles, through: :article_tag_relations, dependent: :destroy

  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :scores, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :itemimage_tags, dependent: :destroy
  accepts_nested_attributes_for :items

  attachment :image
  attachment :itemimage

  validates :name, presence: true

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guest_user"

    end
  end

  def favorite?(article)
    favorites.where(article_id: article).exists?
  end

end

app/controllers/admins/quizzes_controller.rb
class Admins::QuizzesController < ApplicationController
  before_action :authenticate_admin!

  def index
    case (params[:sort])
    when "0"
      @quizzes = Quiz.where(level: "初級").order("updated_at DESC").page(params[:page]).per(10)
      @quiz_level = "初級"
    when "1"
      @quizzes = Quiz.where(level: "中級").order("updated_at DESC").page(params[:page]).per(10)
      @quiz_level = "中級"
    else
      @quizzes = Quiz.where(level: "上級").order("updated_at DESC").page(params[:page]).per(10)
      @quiz_level = "上級"
    end

    @quiz = Quiz.new
  end

  def create
    @quiz = Quiz.new(quiz_params)
    if @quiz.save
      redirect_to admins_quizzes_path(sort: Quiz.levels[@quiz.level])
    else
      @quizzes = Quiz.where(level: "初級").page(params[:page]).per(10)
      render "index"
    end
  end

  def edit
    @quiz = Quiz.find(params[:id])
  end

  def update
    @quiz = Quiz.find(params[:id])
    if @quiz.update(quiz_params)
      redirect_to admins_quizzes_path(sort: Quiz.levels[@quiz.level])
    else
      render "edit"
    end
  end

  def destroy
    quiz = Quiz.find(params[:id])
    quiz.destroy
    redirect_to admins_quizzes_path(sort: 0)
  end

  private

    def quiz_params
      params.require(:quiz).permit(:question, :choice1, :choice2, :choice3, :choice4, :answer, :level)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters,if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admins_articles_path
    when User
      user_path(current_user)
    end
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @admin_articles = Article.where(user_id: nil).limit(15).order("created_at DESC")
    @user_articles = Article.where(admin_id: nil).limit(15).order("created_at DESC")
  end

  def about
  end

end

app/helpers/admins/articles_helper.rb
module Admins::ArticlesHelper
end

app/helpers/admins/contacts_helper.rb
module Admins::ContactsHelper
end

app/helpers/admins/quizzes_helper.rb
module Admins::QuizzesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/quizzes/_quiz-form.html.erb
<%= form_with model: quiz, local:true do |f| %>

  <%= render "layouts/errors", obj: quiz %>

  <table class="table table-borderless quiz-table mb-0 p-5 bg-white">
    <tbody>
      <tr>
        <td width="20%"><%= f.label :question %></td>
        <td width="80%"><%= f.text_area :question, autofocus: true, rows:2, class:"form-control" %></td>
      </tr>
      <tr>
        <td><%= f.label :choice1 %></td>
        <td><%= f.text_field :choice1, class:"form-control" %></td>
      </tr>
      <tr>
        <td><%= f.label :choice2 %></td>
        <td><%= f.text_field :choice2, class:"form-control" %></td>
      </tr>
      <tr>
        <td><%= f.label :choice3 %></td>
        <td><%= f.text_field :choice3, class:"form-control" %></td>
      </tr>
      <tr>
        <td><%= f.label :choice4 %></td>
        <td><%= f.text_field :choice4, class:"form-control" %></td>
      </tr>
      <tr>
        <td><%= f.label :answer %></td>
        <td><%= f.number_field :answer, min: 1, max: 4 %></td>
      </tr>
      <tr>
        <td><%= f.label :level %></td>
        <td><%= f.select :level, Quiz.levels.keys, {include_blank: true} %></td>
      </tr>
    </tbody>
  </table>

  <div class="d-flex justify-content-end p-3 bg-white">
    <%= f.submit "作成", class:"btn btn-lg btn-success px-5" %>
  </div>

<% end %>

app/views/admins/quizzes/edit.html.erb
<div class="container pt-5">
  <div class="row d-flex flex-column align-items-center pt-5">

    <h1 class="pb-4 mb-4">クイズ編集</h1>
    <div class="col-md-8 bg-white p-4">
      <%= form_with model: @quiz, url: admins_quiz_path(@quiz), local:true do |f| %>
        <%= render "quiz-form", quiz: @quiz %>
      <% end %>
    </div>

  </div>
</div>

app/views/admins/quizzes/index.html.erb
<div class="container pt-5">
  <div class="row d-flex pt-5">

    <div class="col-md-5">
      <h1 class="pb-4 mb-4">クイズ作成</h1>

      <%= form_with model: @quiz, url: admins_quizzes_path, local: true do |f| %>
        <%= render "quiz-form", quiz: @quiz %>
      <% end %>
    </div>

    <div class="col-md-7">
      <h1 class="pb-3">問題一覧</h1>

      <div class="mb-5">
        <%= link_to "初級", admins_quizzes_path(sort: 0), class:"btn btn-success btn-lg px-4 mr-3" %>
        <%= link_to "中級", admins_quizzes_path(sort: 1), class:"btn btn-primary btn-lg px-4 mr-3" %>
        <%= link_to "上級", admins_quizzes_path, class:"btn btn-danger px-4" %>
      </div>

      <h2 class="pb-3"><<%= @quiz_level %>問題></h2>

      <% @quizzes.each do |quiz| %>

        <div class="d-flex align-items-center my-3">
          <h3 class="mr-3"><%= quiz.question %></h3>
          <span class=" ml-auto mr-3 "><%= link_to "編集",  edit_admins_quiz_path(quiz), class:"btn btn-success btn-lg text-nowrap" %></span>
          <%= link_to "削除", admins_quiz_path(quiz), method: :delete, data: { confirm: '本当に削除しますか？' }, class:"btn btn-danger btn-lg text-nowrap" %>
        </div>

        <div class="border-bottom d-flex justify-content-between pt-3 h4">
          <p><%= quiz.choice1 %></p>
          <p><%= quiz.choice2 %></p>
          <p><%= quiz.choice3 %></p>
          <p><%= quiz.choice4 %></p>
        </div>

      <% end %>

      <%= paginate @quizzes %>
    </div>

  </div>
</div>

app/views/homes/_article-slide.html.erb
<div class="swiper-container mt-4">
  <div class="swiper-wrapper">

    <% obj.each do |article| %>
      <div class="swiper-slide shadow bg-light">
        <%= link_to article_path(article) do %>
          <%= attachment_image_tag article, :image, class:"img-fluid", fallback: 'img/no_image.png' %>
          <p class="mt-3 px-4 swiper-article-title"><%= article.title %></p>
          <div class="d-flex justify-content-end"><p class="badge badge-secondary mr-3"><%= article.level %></p></div>
        <% end %>
      </div>
    <% end %>

  </div>

 <div class="swiper-button-next swiper-button-black"></div>
 <div class="swiper-button-prev swiper-button-black"></div>

</div>

app/views/homes/about.html.erb
<div class="container">

  <h1 class="font-weight-bold my-5">当サイトのご利用について</h1>
  <ul class="about-prologue">
    <li>B(est) S(martphone) L(ife)はモバイル通信やガジェットなどに関する情報サイトです。</li>
    <li>会員登録なしでも記事をご覧頂けます。</li>
    <li>会員登録後にクイズを受けていただくと知識レベルに応じた投稿がレコメンドされるようになります。</li>
    <li>モバイル知識拡充により、より良いスマートライフの実現をを目指しましょう！</li>
    <li>テストのスコアが上級者レベルになると記事の投稿が出来るようになります。ぜひあなたの知識をシェアしてください！</li>
  </ul>

  <div class="row shadow-lg d-flex about-content">
    <span class="col-md-4 about-image1"></span>
    <div class="col-md-8 bg-white about-text">
      <h1 class="font-weight-bold about-text-title">こんな経験はありませんか？</h1>
      <ul class="about-text-sentence">
        <li>コンテンツのレベル高くて理解できなかった</li>
        <li>それを読むために必要な前提知識が無いことに途中で気づいた</li>
        <li>読み切れてもあまり理解出来ず、<span class="text-danger">時間を無駄にしてしまった</span></li>
      </ul>
    </div>
  </div>

  <div class="row shadow-lg d-flex flex-row-reverse fadein about-content">
    <span class="col-md-4 about-image2"></span>
    <div class="col-md-8 bg-white about-text">
      <h1 class="font-weight-bold about-text-title">自分に合ったコンテンツ</h1>
      <ul class="about-text-sentence">
        <li>会員登録をするとクイズを受けられます</li>
        <li>ぜひ今の知識レベルを確認してください</li>
        <li>一覧やマイページを読み漁りレベルアップを目指しましょう</li>
        <li><span class="text-danger">知れば知るほど面白い（きっと）</span></li>
      </ul>
    </div>
  </div>

  <div class="row shadow-lg d-flex fadein about-content">
    <span class="col-md-4 about-image3"></span>
    <div class="col-md-8 bg-white about-text">
      <h1 class="font-weight-bold about-text-title">最適解を探そう！</h1>
      <ul class="about-text-sentence">
        <li>料金プランや機種、キャリア、ガジェットを見直そう</li>
        <li><span class="text-danger">「何となく」「勧められたから」「長く使っているから」</span><br>以外の理由をあなたはもう見つけられるはず</li>
        <li>あとは自分の最適解を探すのみ</li>
      </ul>
    </div>
  </div>

  <div class="row shadow-lg d-flex flex-row-reverse fadein about-content">
    <span class="col-md-4 about-image4"></span>
    <div class="col-md-8 bg-white about-text">
      <h1 class="font-weight-bold about-text-title">＋α</h1>
      <ul class="about-text-sentence">
        <li>Iot？ eSIM？ DSDS？ Sub6？ ミリ波？ SAR?</li>
        <li>知っているといいことあるかも</li>
      </ul>
    </div>
  </div>

</div>

app/views/homes/top.html.erb
<div id="logo_loader" class="open">
  <div class="f_logo">
    <h1>comfortable smart life for you</h1>
    <h1>Now Loading</h1>
  </div>
</div>

<div class="container pt-5">
  <div class="row">

    <%= render partial: 'layouts/flash' %>

    <div class="col-md-12 mx-auto d-flex justify-content-center align-items-center top-image">
      <div class="col-md-6 text-center d-flex flex-column justify-content-center bg-white top-group">
        <p class="top-text">なにえらぶ？</p>
        <p class="top-text">どれつかう？</p>
        <p class="top-text mb-0 pb-3 border-bottom">考えて選ぶたのしみを</p>

        <p class="top-sentence mt-3">スマホが必須の時代なら</p>
        <p class="top-sentence">「なんとなく」ではなくしっかり選んで使ったほうがいいかもしれません</p>
        <p class="top-sentence">そのお手伝いをするための情報サイトです。</p>
        <p class="top-sentence">くわしくは<%= link_to "コチラ", about_path %></p>
      </div>
    </div>

  </div>
</div>

<div class="container">

  <div class="row d-flex align-items-center mt-5">
    <h1>運営　新着記事</h1>
    <%= render 'layouts/search-bar' %>
  </div>
  <%= render 'homes/article-slide', obj: @admin_articles %>

  <h1 class="mt-5">会員　新着投稿・記事</h1>
  <%= render 'homes/article-slide', obj: @user_articles %>

  <h1 class="my-5"><%= link_to "みんなのアイテム", items_path, class:"border-bottom border-dark" %></h1>

</div>