config/routes.rb
Rails.application.routes.draw do

  root to:  'homes#top'
  get '/about' => 'homes#about'

  devise_for :admins, controllers: {
  sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
  sessions: 'public/users/sessions',
  registrations: 'public/users/registrations',
  passwords: 'public/users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/users/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :articles do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update]
    resources :quizzes, only: [:new, :create, :show]
    resources :contacts, only: [:new, :create, :show]
    resources :searches, only: [:index]
    resources :items, only: [:index]
    resources :favorites, only: [:create, :destroy]
  end

  namespace :admins do
    resources :articles
    resources :quizzes, only: [:index, :create, :edit, :update, :destroy]
    resources :contacts, only: [:index, :show]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :rememberable,
         :validatable#, :recoverable#, :registerable

  has_many :articles, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user, optional: true
  belongs_to :admin, optional: true
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :article_tag_relations, dependent: :destroy
  has_many :tags, through: :article_tag_relations, dependent: :destroy

  attachment :image

  enum level: { 初級: 0, 中級: 1, 上級: 2 }

  validates :title, presence: true, length: {maximum: 50}
  validates :body, presence: true
  validates :level, presence: true

  def reading_time
    reading_time = body.length / 300
    if reading_time < 1
      p "読了目安時間 1分以内"
    else
      p ("読了目安時間 #{reading_time}分")
    end
  end


  def self.search(search)
    Article.where(['title LIKE ?', "%#{search}%"])
  end

end

app/models/article_tag_relation.rb
class ArticleTagRelation < ApplicationRecord

  belongs_to :article
  belongs_to :tag

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :article

  validates :comment, presence: true
  
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :title, presence: true, length: {maximum: 50}
  validates :message, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :article
  
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user

end

app/models/itemimage_tag.rb
class ItemimageTag < ApplicationRecord
  
  belongs_to :user
  
end

app/models/quiz.rb
class Quiz < ApplicationRecord

  has_many :results, dependent: :destroy

  validates :question, presence: true
  validates :choice1, presence: true
  validates :choice2, presence: true
  validates :answer, presence: true
  validates :level, presence: true

  enum level: { 初級: 0, 中級: 1, 上級: 2 }

  def get_answer
    eval("choice#{answer}")
  end

  class << self

    def quiz_set
      low = Quiz.where(level: '初級').sample(10)
      middle = Quiz.where(level: '中級').sample(10)
      high = Quiz.where(level: '上級').sample(10)
      set = low + middle + high
      set.sort
    end

  end

end

app/models/result.rb
class Result < ApplicationRecord
  before_create :judge_answer

  belongs_to :score
  belongs_to :quiz

  validates :selection_result, presence: true

  def judge_answer
    quiz = Quiz.find(self.quiz_id)
    if selection_result == quiz.answer
      self.judgement = 'true'
    else
      self.judgement = 'false'
    end
  end

end

app/models/score.rb
class Score < ApplicationRecord

  belongs_to :user
  has_many :results, dependent: :destroy
  accepts_nested_attributes_for :results

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :article_tag_relations, dependent: :destroy
  has_many :articles, through: :article_tag_relations, dependent: :destroy

  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :scores, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :itemimage_tags, dependent: :destroy
  accepts_nested_attributes_for :items

  attachment :image
  attachment :itemimage

  validates :name, presence: true

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guest_user"

    end
  end

  def favorite?(article)
    favorites.where(article_id: article).exists?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters,if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admins_articles_path
    when User
      user_path(current_user)
    end
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @admin_articles = Article.where(user_id: nil).limit(15).order("created_at DESC")
    @user_articles = Article.where(admin_id: nil).limit(15).order("created_at DESC")
  end

  def about
  end

end

app/helpers/admins/articles_helper.rb
module Admins::ArticlesHelper
end

app/helpers/admins/quizzes_helper.rb
module Admins::QuizzesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li class="error"><span class="error-message"><%= message %></span></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <p class="alert alert-<%= key %>">
    <%= value %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="border-dark border-top d-flex flex-column align-items-center justify-content-center bg-dark">
  <div class="container">
    <div div="row">
      
      <div class="text-center">
        <%= link_to "このサイトについて", about_path, class:"text-white font-weight-bold mr-5 h4" %>
        <%= link_to "お問い合わせ", new_contact_path, class:"text-white font-weight-bold ml-5 h4" %>
      </div>
    
      <p class="copyright mb-0 mt-5 text-white font-weight-bold text-center h5">© 2021 ryota35</p>
    
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header sticky-top d-flex align-items-center">
  <div class="container">

    <nav class="navbar navbar-light navbar-expand-md nav-bg mb-0">
      <%= link_to root_path do %>
        <h1 class="logo pull-left bsl">B S L</h1>
      <% end %>

      <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#responsiveMenu" aria-controls="responsiveMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="responsiveMenu">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li><%= link_to "About", about_path, class: 'border border-dark rounded nav-link mr-4 p-4' %></li>
            <li><%= link_to "記事一覧", articles_path, class: 'border border-dark rounded nav-link mr-4 p-4' %></li>
            <li><%= link_to "クイズ", new_quiz_path, class: 'border border-dark rounded nav-link mr-4 p-4' %></li>
            <li><%= link_to "マイページ", user_path(current_user), class: 'border border-dark rounded nav-link mr-4 p-4' %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'border border-dark rounded nav-link mr-4 p-4' %></li>
            <li><%= link_to "お問い合わせ", new_contact_path, class: 'border border-dark rounded nav-link p-4' %></li>
          <% elsif admin_signed_in? %>
            <li><%= link_to "記事一覧", admins_articles_path, class: 'border border-dark rounded nav-link mr-4 p-4' %></li>
            <li><%= link_to "クイズ問題一覧", admins_quizzes_path(sort: 0), class: 'border border-dark rounded nav-link mr-4 p-4' %></li>
            <li><%= link_to "問い合わせ一覧", admins_contacts_path, class: 'border border-dark rounded nav-link mr-4 p-4' %></li>
            <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'border border-dark rounded nav-link p-4' %></li>
          <% else %>
            <li><%= link_to "About", about_path, class: 'border border-dark rounded nav-link mr-4 p-4' %></li>
            <li><%= link_to "記事一覧", articles_path, class: 'border border-dark rounded nav-link mr-4 p-4' %></li>
            <li><%= link_to "ログイン", new_user_session_path, class: 'border border-dark rounded nav-link mr-4 p-4' %></li>
            <li><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: 'border border-dark rounded nav-link mr-4 p-4' %></li>
            <li><%= link_to "会員登録", new_user_registration_path, class: 'border border-dark rounded nav-link mr-4 p-4' %></li>
            <li><%= link_to "お問い合わせ", new_contact_path, class: 'border border-dark rounded nav-link p-4' %></li>
          <% end %>
        </ul>
      </div>
    </nav>

  </div>
</header>

app/views/layouts/_search-bar.html.erb
<div class="mr-5 ml-auto">
  <%= form_tag(searches_path,method: :get) do %>
    <span class="mr-3"><%= text_field_tag :search, "", placeholder: "何かお探しですか？", size:30 %></span>
    <%= submit_tag '検索', class:"btn-sm" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Best Smartphone Life</title>
    <%= favicon_link_tag('img/favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <div class="main">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

  </body>

</html>