config/routes.rb
Rails.application.routes.draw do

  root to:  'homes#top'
  get '/about' => 'homes#about'

  devise_for :admins, controllers: {
  sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
  sessions: 'public/users/sessions',
  registrations: 'public/users/registrations',
  passwords: 'public/users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/users/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :articles do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update]
    resources :quizzes, only: [:new, :create, :show]
    resources :contacts, only: [:new, :create, :show]
    resources :searches, only: [:index]
    resources :items, only: [:index]
    resources :favorites, only: [:create, :destroy]
  end

  namespace :admins do
    resources :articles
    resources :quizzes, only: [:index, :create, :edit, :update, :destroy]
    resources :contacts, only: [:index, :show]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :rememberable,
         :validatable#, :recoverable#, :registerable

  has_many :articles, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user, optional: true
  belongs_to :admin, optional: true
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :article_tag_relations, dependent: :destroy
  has_many :tags, through: :article_tag_relations, dependent: :destroy

  attachment :image

  enum level: { 初級: 0, 中級: 1, 上級: 2 }

  validates :title, presence: true, length: {maximum: 50}
  validates :body, presence: true
  validates :level, presence: true

  def reading_time
    reading_time = body.length / 300
    if reading_time < 1
      p "読了目安時間 1分以内"
    else
      p ("読了目安時間 #{reading_time}分")
    end
  end


  def self.search(search)
    Article.where(['title LIKE ?', "%#{search}%"])
  end

end

app/models/article_tag_relation.rb
class ArticleTagRelation < ApplicationRecord

  belongs_to :article
  belongs_to :tag

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :article

  validates :comment, presence: true
  
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :title, presence: true, length: {maximum: 50}
  validates :message, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :article
  
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user

end

app/models/itemimage_tag.rb
class ItemimageTag < ApplicationRecord
  
  belongs_to :user
  
end

app/models/quiz.rb
class Quiz < ApplicationRecord

  has_many :results, dependent: :destroy

  validates :question, presence: true
  validates :choice1, presence: true
  validates :choice2, presence: true
  validates :answer, presence: true
  validates :level, presence: true

  enum level: { 初級: 0, 中級: 1, 上級: 2 }

  def get_answer
    eval("choice#{answer}")
  end

  class << self

    def quiz_set
      low = Quiz.where(level: '初級').sample(10)
      middle = Quiz.where(level: '中級').sample(10)
      high = Quiz.where(level: '上級').sample(10)
      set = low + middle + high
      set.sort
    end

  end

end

app/models/result.rb
class Result < ApplicationRecord
  before_create :judge_answer

  belongs_to :score
  belongs_to :quiz

  validates :selection_result, presence: true

  def judge_answer
    quiz = Quiz.find(self.quiz_id)
    if selection_result == quiz.answer
      self.judgement = 'true'
    else
      self.judgement = 'false'
    end
  end

end

app/models/score.rb
class Score < ApplicationRecord

  belongs_to :user
  has_many :results, dependent: :destroy
  accepts_nested_attributes_for :results

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :article_tag_relations, dependent: :destroy
  has_many :articles, through: :article_tag_relations, dependent: :destroy

  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :scores, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :itemimage_tags, dependent: :destroy
  accepts_nested_attributes_for :items

  attachment :image
  attachment :itemimage

  validates :name, presence: true

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guest_user"

    end
  end

  def favorite?(article)
    favorites.where(article_id: article).exists?
  end

end

app/controllers/admins/articles_controller.rb
class Admins::ArticlesController < ApplicationController
  before_action :authenticate_admin!

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.admin_id = current_admin.id
    if @article.save
      redirect_to admins_article_path(@article)
    else
      render "new"
    end
  end

  def index
    @articles = Article.where(user_id: nil).page(params[:page]).per(15).order("created_at DESC")
  end

  def show
    @article = Article.find(params[:id])
    @reading_time = @article.reading_time
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to admins_article_path(@article)
    else
      render "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admins_articles_path
  end


  private

    def article_params
      params.require(:article).permit(:title, :body, :level, :image, tag_ids: [])
    end

end

app/controllers/admins/quizzes_controller.rb
class Admins::QuizzesController < ApplicationController
  before_action :authenticate_admin!

  def index
    case (params[:sort])
    when "0"
      @quizzes = Quiz.where(level: "初級").order("updated_at DESC").page(params[:page]).per(10)
      @quiz_level = "初級"
    when "1"
      @quizzes = Quiz.where(level: "中級").order("updated_at DESC").page(params[:page]).per(10)
      @quiz_level = "中級"
    else
      @quizzes = Quiz.where(level: "上級").order("updated_at DESC").page(params[:page]).per(10)
      @quiz_level = "上級"
    end

    @quiz = Quiz.new
  end

  def create
    @quiz = Quiz.new(quiz_params)
    if @quiz.save
      redirect_to admins_quizzes_path(sort: Quiz.levels[@quiz.level])
    else
      @quizzes = Quiz.where(level: "初級").page(params[:page]).per(10)
      render "index"
    end
  end

  def edit
    @quiz = Quiz.find(params[:id])
  end

  def update
    @quiz = Quiz.find(params[:id])
    if @quiz.update(quiz_params)
      redirect_to admins_quizzes_path(sort: Quiz.levels[@quiz.level])
    else
      render "edit"
    end
  end

  def destroy
    quiz = Quiz.find(params[:id])
    quiz.destroy
    redirect_to admins_quizzes_path(sort: 0)
  end

  private

    def quiz_params
      params.require(:quiz).permit(:question, :choice1, :choice2, :choice3, :choice4, :answer, :level)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters,if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admins_articles_path
    when User
      user_path(current_user)
    end
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @admin_articles = Article.where(user_id: nil).limit(15).order("created_at DESC")
    @user_articles = Article.where(admin_id: nil).limit(15).order("created_at DESC")
  end

  def about
  end

end

app/helpers/admins/articles_helper.rb
module Admins::ArticlesHelper
end

app/helpers/admins/contacts_helper.rb
module Admins::ContactsHelper
end

app/helpers/admins/quizzes_helper.rb
module Admins::QuizzesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/articles/edit.html.erb
<div class="container pt-5">
  <div class="row">

    <div class="col-md-8">
      <%= form_with model: @article, url: admins_article_path, local: true do |f| %>
        <%= render "layouts/errors", obj: @article %>
        <div class="form-group">
          <%= f.label :image, class:"contact-title" %><br>
          <%= f.attachment_field :image %>
        </div>

        <div class="form-group mt-5">
          <%= f.label :"タイトル(50文字まで)", class:"contact-title" %><br>
          <%= f.text_field :title, autofocus: true, class:"form-control form-control-lg js-text" %><br>
          <div class="d-flex justify-content-end"><p class="js-text-count h5"></p></div>
        </div>

        <div class="form-group mt-3">
          <%= f.label :body, class:"contact-title" %><br>
          <%= f.text_area :body, class:"form-control", rows:20 %>
        </div>

        <div class="form-group mt-5">
          <span class="mr-3"><%= f.label :level, class:"contact-title" %></span>
          <%= f.select :level, Article.levels.keys, {prompt: "選択して下さい"} %>
        </div>

        <div class="form-group mt-3">
          <%= f.label :タグ（複数選択可）, class:"contact-title" %><br>
          <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class="d-inline mr-1"><%= tag.label { tag.check_box + tag.text } %></div>
          <% end %>
        </div>

        <div class="d-flex justify-content-end">
          <%= f.submit "編集完了", class:"btn btn-success btn-lg mt-3 px-5 py-3" %>
        </div>
      <% end %>
    </div>

    <div class="col-md-4 border-left border-secondary precautions">
      <h1>ご投稿の際の注意事項</h1>
      <ul class="precautions-ul mt-4 ml-3">
        <li>公序良俗に反しない内容であること</li>
        <li>著作権、肖像権等を侵害しないこと</li>
        <li>誹謗・中傷する内容でないこと</li>
        <li>個人情報は投稿しないこと</li>
        <li>タイトルと本文はなるべく食い違わないようにすること</li>
        <li>商用の宣伝などをしないこと</li>
        <li>事実ではなく、予想や推論を投稿する場合にはそれを明記すること</li>
      </ul>
    </div>

  </div>
</div>

app/views/admins/articles/index.html.erb
  <div class="container">

    <div class="row d-flex align-items-center pt-5">

      <h1 class="ml-5">Latest Articles(管理者のみ表示)</h1>
      <%= render partial: 'layouts/flash' %>

      <div class="d-flex align-items-center ml-auto">
        <%= link_to  new_admins_article_path, class: 'btn border border-dark mr-5 bg-light' do %>
          <i class="fas fa-edit"></i>
          <p class="mb-0">記事を書く</p>
        <% end %>
        <%= render 'layouts/search-bar' %>
      </div>

    </div>

    <div class="row">
      <div class="col-md-9 mt-3">
        <table class="table table-hover bg-white shadow">
          <tbody>
            <% @articles.each do |article| %>
              <tr class="mt-3">
            　   <td class="p-0"><%= link_to admins_article_path(article) do %><%= attachment_image_tag article, :image, :fill, 128, 72, format: 'jpeg', fallback: 'img/no_image.png', size: '128x72' %><% end %></td>
                <td>
                  <p class="h4"><%= link_to article.title, admins_article_path(article) %></p>
                  <div class="text-right">
                    <span class="badge badge-primary"><%= article.level %></span>
                    <% article.tags.each do |tag| %>
                      <span class="badge badge-secondary"><%= tag.name %></span>
                    <% end %>
                    <h6 class="article-show_date">
                      <i class="far fa-clock"></i>&nbsp;&nbsp;<%= article.created_at.strftime('%Y.%m.%d') %>
                    </h6>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @articles %>
      </div>
    </div>

  </div>

app/views/admins/articles/new.html.erb
<div class="container pt-5">
  <div class="row">

    <div class="col-md-8">
      <%= form_with model: @article, url: admins_articles_path, local: true do |f| %>
        <%= render "layouts/errors", obj: @article %>
        <div class="form-group">
          <%= f.label :image, class:"contact-title" %><br>
          <%= f.attachment_field :image %>
        </div>

        <div class="form-group mt-5">
          <%= f.label :"タイトル(50文字まで)", class:"contact-title" %>
          <%= f.text_field :title, autofocus: true, class:"form-control form-control-lg js-text" %>
          <div class="d-flex justify-content-end"><p class="js-text-count h5"></p></div>
        </div>

        <div class="form-group mt-3">
          <%= f.label :body, class:"contact-title" %>
          <%= f.text_area :body, class:"form-control", rows:20 %>
        </div>

        <div class="form-group mt-5">
          <%= f.label :level, class:"contact-title" %>
          <%= f.select :level, Article.levels.keys, {prompt: "選択して下さい"} %>
        </div>

        <div class="form-group mt-5">
          <%= f.label :タグ（複数選択可）, class:"contact-title" %>
          <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class="d-inline mr-1"><%= tag.label { tag.check_box + tag.text } %></div>
          <% end %>
        </div>

        <div class="d-flex justify-content-end"><%= f.submit "投稿する", class:"btn btn-success btn-lg mt-3 px-5 py-3" %></div>

      <% end %>
    </div>

    <div class="col-md-4 border-left border-secondary precautions">
      <h1>ご投稿の際の注意事項</h1>
      <ul class="precautions-ul mt-4 ml-3">
        <li>公序良俗に反しない内容であること</li>
        <li>著作権、肖像権等を侵害しないこと</li>
        <li>誹謗・中傷する内容でないこと</li>
        <li>個人情報は投稿しないこと</li>
        <li>タイトルと本文はなるべく食い違わないようにすること</li>
        <li>商用の宣伝などをしないこと</li>
        <li>事実ではなく、予想や推論を投稿する場合にはそれを明記すること</li>
      </ul>
    </div>

  </div>
</div>

app/views/admins/articles/show.html.erb
<div class="container">

  <div class="row d-flex flex-column align-items-center mt-5">
    <%= render partial: 'layouts/flash' %>
    <div class="col-md-7 shadow p-0 bg-white">

      <div class="text-center"><%= attachment_image_tag @article, :image, class:"img-fluid", fallback: 'img/no_image.png' %></div>

      <div class="d-flex align-items-center mt-4 ml-3">
        <h2 class="font-weight-bold flex-grow-1 mr-3"><%= @article.title%></h2>
      </div>

      <span class="badge badge-primary mt-2 ml-3"><%= @article.level%></span>

      <div class="ml-3">
        <% @article.tags.each do |tag| %>
          <span class= 'badge badge-secondary'><%= tag.name %></span>
        <% end %>
      </div>

      <p class="font-weight-bold mt-2 mr-5 h5 text-right"><%= @reading_time %></p>

      <p class="article-body mt-5 mx-4"><%= safe_join(@article.body.split("\n"),tag(:br)) %></p>

      <h5 class="article-show_date text-right mr-3">
        <i class="far fa-clock"></i>&nbsp;&nbsp;<%= @article.created_at.strftime('%Y.%m.%d') %>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <i class="fa fa-history "></i>&nbsp;&nbsp;<%= @article.updated_at.strftime('%Y.%m.%d') %>
      </h5>

      <div class="text-right mt-3">
        <%= link_to "編集",  edit_admins_article_path(@article), class:"btn btn-lg btn-success px-4 mr-3" %>
        <%= link_to "削除", admins_article_path(@article), method: :delete, data: { confirm: '本当に削除しますか？' }, class:"btn btn-lg btn-danger px-4" %>
      </div>

    </div>
  </div>
</div>